### ISSUE TITLE
Test criteria question

### ISSUE THREAD

**Issue by Yupjun** [NomaDamas/KICE_slayer_AI_Korean#26]
안녕하세요 혹시 모델의 생성 결과와 실제 결과를 평가 할 떄 exact match로만 하시나요?
예를들어 생성된 결과가 "1 입니다" 이고 실제 테스트 정답이 "1" 인 경우 에는 어떻게 하시는지 궁금합니다.

**Comment by vkehfdl1** [comment]
@Yupjun 안녕하세요.
오리지날 코드에서는 "수동 채점"을 통하여 채점했습니다. 즉, 서술형으로 답한 것에서 몇 번으로 LLM이 정답을 내뱉었는지 파악하고 직접 채점했습니다,
AutoRAG를 사용한 코드에서는 "gpt-4o-mini"를 통하여 자동 채점합니다. 이 경우에도 LLM이 몇 번을 정답으로 도출했는지 파악하여 채점합니다,
